name: Auto Create Draft PR

on:
  push:
    branches-ignore:
      - main
      - master
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = process.env.GITHUB_REF.replace('refs/heads/', '');
            if (branch !== 'main' && branch !== 'master' && branch !== 'develop') {
              // 检查是否已存在从该分支到 main 的 PR，避免重复创建
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branch}`,
                base: 'main',
                state: 'open',
              });
              if (prs.data.length === 0) {
                await github.rest.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: `draft: ${branch}`,
                  head: branch,
                  base: 'main',
                  body: `This PR was automatically created from branch \`${branch}\`.\n\n**Commit:** ${{ github.sha }}\n**Branch:** \`${branch}\`\n\nThis is a draft PR. Please review and update as needed.`,
                  draft: true
                });
              } else {
                console.log('PR already exists for this branch.');
              }
            }
